### ISSUE TITLE
[FEAT] Enable/Disable notifications via API

### ISSUE THREAD

**Issue by duylong** [skrashevich/double-take#229]
Hi,

I would like to control the management of notifications with my alarm system. So I would like to enable notifications only when I'm not at home. Currently, the configuration is static and it is not possible to easily manage notifications.

The ability to enable or disable notifications from the API would be very practical.

For example :
<pre>
http://localhost:3000/api/notify/gotify/disable
http://localhost:3000/api/notify/gotify/enable
http://localhost:3000/api/notify/gotify/status
</pre>

Best regards,

**Comment by skrashevich** [comment]
As a temporary solution, added the detector enable setting to the configuration: https://github.com/skrashevich/double-take/pull/194/commits/d76d6a62dc808d7cd2cd276e00a693c4628ae26d

**Comment by duylong** [comment]
> As a temporary solution, added the detector enable setting to the configuration: https://github.com/skrashevich/double-take/commit/d76d6a62dc808d7cd2cd276e00a693c4628ae26d

This temporary solution that you indicated to me cannot be controlled remotely.

**Comment by duylong** [comment]
Any news for this feature ?

**Comment by AndLindemann** [comment]
I'd also like to enable/disable detectors via API (or HA entity). It'd help saving some money by not sending images to AWS Recognition in situations where the resulting detection wouldn't trigger anything anyway. Currently I only need recognition to run when I come home. When I'm already at home, and someone else rings the doorbell, the image still gets send to recognition, but it's not necessary for me because I have no use case for that situation. 
So I'd like to be able to stop detection dynamically based on whether I'm at home or not through HA. Would be great if we could use the API for that at least, if adding that through an HA entity boolean is too much work at this time.

**Comment by duylong** [comment]
Too bad this feature wasn't planned.
