### ISSUE TITLE
[BUG] Double take person sensor becomes unavailable after a certain time

### ISSUE THREAD

**Issue by berkansezer77** [skrashevich/double-take#494]
**Describe the bug**
I have a sensor named sensor.double_take_berkan. System works well and sensor is working. But after a certain time (usually 10 minutes) the sensor becomes unavailable. But whenever a camera identifies my face in doubletake the sensor becomes online again. The sensor is always online with [jakowenko](https://github.com/jakowenko) version.

**Version of Double Take**
`1.13.11.8`

**Expected behavior**
The sensor should not become as unavailable. 

**Screenshots**
![image](https://github.com/skrashevich/double-take/assets/84282504/99fd9dfa-4d4b-4192-b3fa-3ce9d7dc7381).

**Hardware**
 - Beelink SEI Core i5

**Comment by RogerSelwyn** [comment]
I also have this. It goes unavailable exactly at 600 seconds, presumable because of this config for the sensor:

`{"name":"clare","object_id":"double_take_clare","icon":"mdi:account","value_template":"{{ value_json.camera }}","state_topic":"homeassistant/sensor/double-take/clare/state","json_attributes_topic":"homeassistant/sensor/double-take/clare/state","availability_topic":"double-take/available","unique_id":"double_take_clare","expire_after":600}`
