### ISSUE TITLE
[FEAT] Deepface

### ISSUE THREAD

**Issue by townsmcp** [skrashevich/double-take#50]
**Is your feature request related to a problem? Please describe.**
Any chance of integrating Deepface as a detector?

Requests on Jakowenko for the integration are:
https://github.com/jakowenko/double-take/issues/196
https://github.com/jakowenko/double-take/issues/305

**Comment by skrashevich** [comment]
I have recently pondered upon this matter. Unfortunately, DeepFace operates on a different logic: it lacks the ability to learn and memorize faces as such, essentially it only has the capacity to assess the degree of similarity between two given photographs. Therefore, maintaining a database of trained faces should be implemented on the side of double-take; I am unsure if this aligns with the objective of this software.
Please do correct me if I am mistaken in any way.

**Comment by townsmcp** [comment]
Is anything here of any use?
https://viso.ai/computer-vision/deepface/

**Comment by skrashevich** [comment]
> Is anything here of any use?

Unfortunately, you have just confirmed what I said before. DeepFace is a framework, not a recognition service. I will think about opportunities  for its implementation in this project.

**Comment by townsmcp** [comment]
Ah ok. Sorry, I didnt realise. Im about 2 weeks into all this stuff and still trying to learn - I have a Nest Hello at the moment as doorbell and yesterday I got a Unifi G4 doorbell but want to get all this working properly before I install the G4. For example, I have no idea what the differences on Double Take dashboard are between 'MQTT', 'Snapshot' and 'Latest' are meant to mean for an image; no idea which one is supposed to be the better image type and then which one('s) to try to stop coming into Double Take

**Comment by skrashevich** [comment]
> 'MQTT', 'Snapshot' and 'Latest'

"Snapshot" -- frame from frigate, saved then frigate detect an event (motion, for example)
"Latest" -- frame from camera, on the moment then double-take trying to make an recognition (Usually, the difference between them is 1-2 seconds)
"MQTT" -- The frame that the frigate transmitted with the event by MQTT protocol. It's usually equivalent to "snapshot", but depends on frigate settings

The current crazy zoo of methods is due to historical reasons. If u use double-take in conjunction with frigate, the "snapshot" method will be enough
